config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :tutor

  def self.search(search)
    where("tutor_id LIKE ?","%#{search}%")
  end
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    if params[:student][:tutor_id]
      @students = Student.search(params[:student][:tutor_id])
    else
      @students = Student.all
    end
  end

  def new
    @student = Student.new
  end
  def show
    @student = Student.find(params[:id])
  end
  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student= Student.find(params[:id])
    if @student.update(student_params)
      redirect_to action: "index"
    end
  end
  def student_params
    params.require(:student).permit(:first_name, :surname, :tutor_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delilah</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<%= form_tag students_path, :method => 'get' do %>
  <%= collection_select :student, :tutor_id, Tutor.all, :id, :name, prompt: true %>
  <%= submit_tag "search" %>
<% end %>

<% @students.each do |n| %>
  <li>
    <%= link_to n.first_name, student_path(n) %>
    <%= n.surname %> ..tutor is...
    <%= n.tutor.name %>
  </li>
 <% end %>

<%= params.inspect %>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>
<%= @student.first_name %>
<%=form_for @student do |v| %>
  <%= v.select(:tutor_id, [[1],[2],[3]])%>
  <%= v.submit "change" %>
<% end %>